packages:
  - apps/*
  - workers/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - argon2
  - esbuild
  - sharp
  - '@parcel/watcher'
  - '@scarf/scarf'
  - msgpackr-extract
  - unrs-resolver
