import { Slot } from '@radix-ui/react-slot'; import { cva, type VariantProps } from 'class-variance-authority'; import type React from 'react'; import { cn } from '@/lib/utils';
const buttonVariants = cva('inline-flex items-center justify-center rounded-lg text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 disabled:pointer-events-none disabled:opacity-50', { variants: { variant: { default: 'bg-cyan-500 text-slate-950 hover:bg-cyan-400', secondary: 'bg-slate-800 text-slate-100 hover:bg-slate-700', outline: 'border border-slate-700 bg-transparent hover:bg-slate-800', destructive: 'bg-red-500 text-white hover:bg-red-400' }, size: { default: 'h-10 px-4 py-2', sm: 'h-8 px-3', lg: 'h-12 px-6' } }, defaultVariants: { variant: 'default', size: 'default' } });
export function Button({ className, variant, size, asChild = false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof buttonVariants> & { asChild?: boolean }) { const Comp = asChild ? Slot : 'button'; return <Comp className={cn(buttonVariants({ variant, size }), className)} {...props} />; }
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-2xl border border-slate-800 bg-slate-900/70 shadow-xl shadow-slate-950/10', className)} {...props} />; }
export function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn('p-5 pb-2', className)} {...props} />; }
export function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn('p-5 pt-3', className)} {...props} />; }
export function Badge({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) { return <span className={cn('inline-flex rounded-full border border-slate-700 bg-slate-800 px-2.5 py-1 text-xs font-medium text-slate-300', className)} {...props} />; }
export function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={cn('h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm outline-none placeholder:text-slate-500 focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500', props.className)} />; }
export function Table({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm">{children}</table></div>; }
